app: serverless-graphql
org: slsplus
stage: dev
component: scf
name: GraphqlServerScf

inputs:
  src: ./
  name: serverless-graphql
  region: ap-guangzhou
  handler: app.handler
  description: serverless graphql function
  memorySize: 128
  timeout: 30
